# Generated by Django 3.2.25 on 2024-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видео с youtube',
                'verbose_name_plural': 'Видео с youtube',
            },
        ),
    ]
