# Generated by Django 3.2.25 on 2024-08-01 19:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_youtubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region='RU', verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('article', models.CharField(default=0, max_length=100, verbose_name='Артикул товара')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонки',
            },
        ),
    ]
