# Generated by Django 3.2.25 on 2024-07-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20240714_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bundling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
    ]
