# Generated by Django 3.2.25 on 2024-07-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
