# Generated by Django 3.2.25 on 2024-07-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productspectype_is_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
