# Generated by Django 3.2.25 on 2024-07-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspectype',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category', verbose_name='Категории, где фильтр будет виден'),
        ),
    ]
