# Generated by Django 3.2.25 on 2024-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productspectype_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspectype',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Category', verbose_name='Категории, где фильтр будет виден'),
        ),
    ]
