# Generated by Django 3.2.25 on 2024-07-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productspectype_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция в навигации'),
        ),
    ]
