# Generated by Django 3.2.25 on 2024-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_category_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspectype',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='catalog.Category', verbose_name='Категории, где фильтр будет виден'),
        ),
    ]
