# Generated by Django 3.2.25 on 2024-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_productspectype_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, related_name='_catalog_category_subcategories_+', to='catalog.Category', verbose_name='Подкатегории'),
        ),
    ]
