# Generated by Django 3.2.25 on 2024-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_productspectype_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspectype',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция в фильтрах'),
        ),
    ]
