# Generated by Django 3.2.25 on 2024-08-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_productspectype_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productspectype', verbose_name='Фильтр')),
            ],
            options={
                'verbose_name': 'Значение фильтра',
                'verbose_name_plural': 'Значения фильтров',
            },
        ),
    ]
