# Generated by Django 3.2.25 on 2024-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20240819_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='_catalog_category_subcategories_+', to='catalog.Category', verbose_name='Подкатегории'),
        ),
    ]
